<?php

/* custom routes generated by CRUD */


Route::group(array('prefix' => 'admin/', 'middleware' => 'admin','as'=>'admin.'), function () {

Route::get('events', ['as'=> 'events.index', 'uses' => 'EventController@index']);
Route::post('events', ['as'=> 'events.store', 'uses' => 'EventController@store']);
	Route::get('events/create', ['as'=> 'events.create', 'uses' => 'EventController@create']);
	Route::get('events/data', ['as'=> 'events.data', 'uses' => 'EventController@data']);
	Route::post('events/data2', ['as'=> 'events.editdata', 'uses' => 'EventController@editData']);
Route::put('events/{events}', ['as'=> 'events.update', 'uses' => 'EventController@update']);
Route::patch('events/{events}', ['as'=> 'events.update', 'uses' => 'EventController@update']);
Route::get('events/{id}/delete', array('as' => 'events.delete', 'uses' => 'EventController@getDelete'));
Route::get('events/{id}/confirm-delete', array('as' => 'events.confirm-delete', 'uses' => 'EventController@getModalDelete'));
Route::get('events/{events}', ['as'=> 'events.show', 'uses' => 'EventController@show']);
Route::get('events/{events}/edit', ['as'=> 'events.edit', 'uses' => 'EventController@edit']);

});


Route::group(array('prefix' => 'admin/', 'middleware' => 'admin','as'=>'admin.'), function () {

Route::get('categories', ['as'=> 'categories.index', 'uses' => 'CategoryController@index']);
Route::post('categories', ['as'=> 'categories.store', 'uses' => 'CategoryController@store']);
Route::get('categories/create', ['as'=> 'categories.create', 'uses' => 'CategoryController@create']);
Route::put('categories/{categories}', ['as'=> 'categories.update', 'uses' => 'CategoryController@update']);
Route::patch('categories/{categories}', ['as'=> 'categories.update', 'uses' => 'CategoryController@update']);
Route::get('categories/{id}/delete', array('as' => 'categories.delete', 'uses' => 'CategoryController@getDelete'));
Route::get('categories/{id}/confirm-delete', array('as' => 'categories.confirm-delete', 'uses' => 'CategoryController@getModalDelete'));
Route::get('categories/{categories}', ['as'=> 'categories.show', 'uses' => 'CategoryController@show']);
Route::get('categories/{categories}/edit', ['as'=> 'categories.edit', 'uses' => 'CategoryController@edit']);

});


Route::group(array('prefix' => 'admin/', 'middleware' => 'admin','as'=>'admin.'), function () {

Route::get('campaigns', ['as'=> 'campaigns.index', 'uses' => 'CampaignController@index']);
Route::post('campaigns', ['as'=> 'campaigns.store', 'uses' => 'CampaignController@store']);
Route::get('campaigns/create', ['as'=> 'campaigns.create', 'uses' => 'CampaignController@create']);
Route::put('campaigns/{campaigns}', ['as'=> 'campaigns.update', 'uses' => 'CampaignController@update']);
Route::patch('campaigns/{campaigns}', ['as'=> 'campaigns.update', 'uses' => 'CampaignController@update']);
Route::get('campaigns/{id}/delete', array('as' => 'campaigns.delete', 'uses' => 'CampaignController@getDelete'));
Route::get('campaigns/{id}/confirm-delete', array('as' => 'campaigns.confirm-delete', 'uses' => 'CampaignController@getModalDelete'));
Route::get('campaigns/{campaigns}', ['as'=> 'campaigns.show', 'uses' => 'CampaignController@show']);
Route::get('campaigns/{campaigns}/edit', ['as'=> 'campaigns.edit', 'uses' => 'CampaignController@edit']);

});


Route::group(array('prefix' => 'admin/', 'middleware' => 'admin','as'=>'admin.'), function () {

Route::get('contacts', ['as'=> 'contacts.index', 'uses' => 'ContactController@index']);
Route::post('contacts', ['as'=> 'contacts.store', 'uses' => 'ContactController@store']);
Route::get('contacts/create', ['as'=> 'contacts.create', 'uses' => 'ContactController@create']);
Route::put('contacts/{contacts}', ['as'=> 'contacts.update', 'uses' => 'ContactController@update']);
Route::patch('contacts/{contacts}', ['as'=> 'contacts.update', 'uses' => 'ContactController@update']);
Route::get('contacts/{id}/delete', array('as' => 'contacts.delete', 'uses' => 'ContactController@getDelete'));
Route::get('contacts/{id}/confirm-delete', array('as' => 'contacts.confirm-delete', 'uses' => 'ContactController@getModalDelete'));
Route::get('contacts/{contacts}', ['as'=> 'contacts.show', 'uses' => 'ContactController@show']);
Route::get('contacts/{contacts}/edit', ['as'=> 'contacts.edit', 'uses' => 'ContactController@edit']);

});


Route::group(array('prefix' => 'admin/', 'middleware' => 'admin','as'=>'admin.'), function () {

Route::get('eventDates', ['as'=> 'eventDates.index', 'uses' => 'EventDateController@index']);
Route::post('eventDates', ['as'=> 'eventDates.store', 'uses' => 'EventDateController@store']);
Route::get('eventDates/create', ['as'=> 'eventDates.create', 'uses' => 'EventDateController@create']);
Route::put('eventDates/{eventDates}', ['as'=> 'eventDates.update', 'uses' => 'EventDateController@update']);
Route::patch('eventDates/{eventDates}', ['as'=> 'eventDates.update', 'uses' => 'EventDateController@update']);
Route::get('eventDates/{id}/delete', array('as' => 'eventDates.delete', 'uses' => 'EventDateController@getDelete'));
Route::get('eventDates/{id}/confirm-delete', array('as' => 'eventDates.confirm-delete', 'uses' => 'EventDateController@getModalDelete'));
Route::get('eventDates/{eventDates}', ['as'=> 'eventDates.show', 'uses' => 'EventDateController@show']);
Route::get('eventDates/{eventDates}/edit', ['as'=> 'eventDates.edit', 'uses' => 'EventDateController@edit']);

});


Route::group(array('prefix' => 'admin/', 'middleware' => 'admin','as'=>'admin.'), function () {

Route::get('contactEvents', ['as'=> 'contactEvents.index', 'uses' => 'Contact_eventController@index']);
Route::post('contactEvents', ['as'=> 'contactEvents.store', 'uses' => 'Contact_eventController@store']);
Route::get('contactEvents/create', ['as'=> 'contactEvents.create', 'uses' => 'Contact_eventController@create']);
Route::put('contactEvents/{contactEvents}', ['as'=> 'contactEvents.update', 'uses' => 'Contact_eventController@update']);
Route::patch('contactEvents/{contactEvents}', ['as'=> 'contactEvents.update', 'uses' => 'Contact_eventController@update']);
Route::get('contactEvents/{id}/delete', array('as' => 'contactEvents.delete', 'uses' => 'Contact_eventController@getDelete'));
Route::get('contactEvents/{id}/confirm-delete', array('as' => 'contactEvents.confirm-delete', 'uses' => 'Contact_eventController@getModalDelete'));
Route::get('contactEvents/{contactEvents}', ['as'=> 'contactEvents.show', 'uses' => 'Contact_eventController@show']);
Route::get('contactEvents/{contactEvents}/edit', ['as'=> 'contactEvents.edit', 'uses' => 'Contact_eventController@edit']);

});


Route::group(array('prefix' => 'admin/', 'middleware' => 'admin','as'=>'admin.'), function () {

Route::get('eventStatuses', ['as'=> 'eventStatuses.index', 'uses' => 'EventStatusController@index']);
Route::post('eventStatuses', ['as'=> 'eventStatuses.store', 'uses' => 'EventStatusController@store']);
Route::get('eventStatuses/create', ['as'=> 'eventStatuses.create', 'uses' => 'EventStatusController@create']);
Route::put('eventStatuses/{eventStatuses}', ['as'=> 'eventStatuses.update', 'uses' => 'EventStatusController@update']);
Route::patch('eventStatuses/{eventStatuses}', ['as'=> 'eventStatuses.update', 'uses' => 'EventStatusController@update']);
Route::get('eventStatuses/{id}/delete', array('as' => 'eventStatuses.delete', 'uses' => 'EventStatusController@getDelete'));
Route::get('eventStatuses/{id}/confirm-delete', array('as' => 'eventStatuses.confirm-delete', 'uses' => 'EventStatusController@getModalDelete'));
Route::get('eventStatuses/{eventStatuses}', ['as'=> 'eventStatuses.show', 'uses' => 'EventStatusController@show']);
Route::get('eventStatuses/{eventStatuses}/edit', ['as'=> 'eventStatuses.edit', 'uses' => 'EventStatusController@edit']);

});


Route::group(array('prefix' => 'admin/', 'middleware' => 'admin','as'=>'admin.'), function () {

Route::get('emails', ['as'=> 'emails.index', 'uses' => 'EmailController@index']);
Route::post('emails', ['as'=> 'emails.store', 'uses' => 'EmailController@store']);
Route::get('emails/create', ['as'=> 'emails.create', 'uses' => 'EmailController@create']);
Route::put('emails/{emails}', ['as'=> 'emails.update', 'uses' => 'EmailController@update']);
Route::patch('emails/{emails}', ['as'=> 'emails.update', 'uses' => 'EmailController@update']);
Route::get('emails/{id}/delete', array('as' => 'emails.delete', 'uses' => 'EmailController@getDelete'));
Route::get('emails/{id}/confirm-delete', array('as' => 'emails.confirm-delete', 'uses' => 'EmailController@getModalDelete'));
Route::get('emails/{emails}', ['as'=> 'emails.show', 'uses' => 'EmailController@show']);
Route::get('emails/{emails}/edit', ['as'=> 'emails.edit', 'uses' => 'EmailController@edit']);

});
